In [1]:
import numpy as np

In [2]:
# creating an array 
a = np.eye(3,3)
b = np.eye(3,3)
c = a + b 
print(c)

[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]


In [34]:
arr = np.array([[1,2,3,4,5],[5,6,7,8,13],[9,10,11,12,500]])
print(arra)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [25]:
print(arr[0:3,1:3])

[[ 2  3]
 [ 6  7]
 [10 11]]


In [35]:
mean = np.mean(arr)
print("Mean: \n", mean)
median = np.median(arr)
print("Median \n :", median)
std = np.std(arr)
print("Std: {:.2f}".format(std))

Mean: 
 39.733333333333334
Median 
 : 7.0
Std: 123.06


In [32]:
normalization = (arr - mean )/std
print("Normalization : {:.2f}", normalization)

Normalization : {:.2f} [[-1.59325501 -1.30357228 -1.01388955 -0.72420682]
 [-0.43452409 -0.14484136  0.14484136  0.43452409]
 [ 0.72420682  1.01388955  1.30357228  1.59325501]]
